server:
  port: 8084

endpoint:
  uf:
    url: '${urlIndicadores:https://api.gael.cloud/general/public/monedas}'

custom:
  rest:
    connection:
      connectionRequestTimeout: '${connectionRequestTimeout:2000}'
      connectTimeout: '${connectTimeout:2000}'
      readTimeout: '${readTimeout:2000}'