package com.devops.dxc.devops.selenium;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class SeleniumLab4Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.out.println("Iniciando configuración...");
    System.setProperty("webdriver.chrome.driver","WEBDRIVER");
    //System.setProperty("webdriver.chrome.driver","drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void seleniumLab4() {

    driver.get("http://localhost:8084/");
    driver.manage().window().setSize(new Dimension(1280, 745));
    driver.findElement(By.linkText("Conoce tu 10%")).click();
    {
      WebElement element = driver.findElement(By.linkText("Conoce tu 10%"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("mat-input-0")).click();
    driver.findElement(By.id("mat-input-0")).sendKeys("1500000");
    driver.findElement(By.id("mat-input-1")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("mat-input-1")).sendKeys("60000000");
    driver.findElement(By.cssSelector(".mat-button-wrapper")).click();
    driver.findElement(By.cssSelector(".mat-raised-button")).click();
  }
}
